export interface ChartRegistryEntry {
  id: string;
  name: string;
  description: string;
  bestFor: string[];
  requiredDimensions: number;
  requiredMeasures: number;
  minimumDataPoints: number;
  maximumRecommendedCategories?: number;
  supportsTimeSeries: boolean;
  supportsCategorical: boolean;
  supportsMultipleSeries: boolean;
  supportsHierarchy: boolean;
  supportsGeography: boolean;
  supportsInteraction: boolean;
  supportsZoom: boolean;
  supportsTooltip: boolean;
  supportsDrilldown: boolean;
  supportsExport: boolean;
}

export const ChartRegistry: Record<string, ChartRegistryEntry> = {
  line: {
    id: "line",
    name: "Line Chart",
    description: "Displays trends and time series data over a continuous interval.",
    bestFor: ["time_series", "trend", "change_over_time"],
    requiredDimensions: 1,
    requiredMeasures: 1,
    minimumDataPoints: 2,
    supportsTimeSeries: true,
    supportsCategorical: false,
    supportsMultipleSeries: true,
    supportsHierarchy: false,
    supportsGeography: false,
    supportsInteraction: true,
    supportsZoom: true,
    supportsTooltip: true,
    supportsDrilldown: false,
    supportsExport: true,
  },
  bar: {
    id: "bar",
    name: "Bar Chart",
    description: "Compares quantities among different categories.",
    bestFor: ["category_comparison", "ranking", "latest_value"],
    requiredDimensions: 1,
    requiredMeasures: 1,
    minimumDataPoints: 1,
    maximumRecommendedCategories: 15,
    supportsTimeSeries: true,
    supportsCategorical: true,
    supportsMultipleSeries: true,
    supportsHierarchy: false,
    supportsGeography: false,
    supportsInteraction: true,
    supportsZoom: true,
    supportsTooltip: true,
    supportsDrilldown: true,
    supportsExport: true,
  },
  grouped_bar: {
    id: "grouped_bar",
    name: "Grouped Bar Chart",
    description: "Compares quantities across multiple sub-categories.",
    bestFor: ["multiple_category_comparison", "subgroup_comparison"],
    requiredDimensions: 1,
    requiredMeasures: 2,
    minimumDataPoints: 1,
    supportsTimeSeries: true,
    supportsCategorical: true,
    supportsMultipleSeries: true,
    supportsHierarchy: false,
    supportsGeography: false,
    supportsInteraction: true,
    supportsZoom: true,
    supportsTooltip: true,
    supportsDrilldown: false,
    supportsExport: true,
  },
  stacked_bar: {
    id: "stacked_bar",
    name: "Stacked Bar Chart",
    description: "Shows composition of total for each category.",
    bestFor: ["composition", "category_contributions"],
    requiredDimensions: 1,
    requiredMeasures: 2,
    minimumDataPoints: 1,
    supportsTimeSeries: true,
    supportsCategorical: true,
    supportsMultipleSeries: true,
    supportsHierarchy: false,
    supportsGeography: false,
    supportsInteraction: true,
    supportsZoom: true,
    supportsTooltip: true,
    supportsDrilldown: false,
    supportsExport: true,
  },
  area: {
    id: "area",
    name: "Area Chart",
    description: "Shows cumulative trends and volume over time.",
    bestFor: ["cumulative_trend", "volume_over_time"],
    requiredDimensions: 1,
    requiredMeasures: 1,
    minimumDataPoints: 2,
    supportsTimeSeries: true,
    supportsCategorical: false,
    supportsMultipleSeries: true,
    supportsHierarchy: false,
    supportsGeography: false,
    supportsInteraction: true,
    supportsZoom: true,
    supportsTooltip: true,
    supportsDrilldown: false,
    supportsExport: true,
  },
  pie: {
    id: "pie",
    name: "Pie Chart",
    description: "Shows part-to-whole relationships.",
    bestFor: ["composition_total", "part_to_whole"],
    requiredDimensions: 1,
    requiredMeasures: 1,
    minimumDataPoints: 2,
    maximumRecommendedCategories: 7,
    supportsTimeSeries: false,
    supportsCategorical: true,
    supportsMultipleSeries: false,
    supportsHierarchy: false,
    supportsGeography: false,
    supportsInteraction: true,
    supportsZoom: false,
    supportsTooltip: true,
    supportsDrilldown: true,
    supportsExport: true,
  },
  donut: {
    id: "donut",
    name: "Donut Chart",
    description: "Shows part-to-whole relationships with a hollow center.",
    bestFor: ["composition_total", "percentage_breakdown"],
    requiredDimensions: 1,
    requiredMeasures: 1,
    minimumDataPoints: 2,
    maximumRecommendedCategories: 7,
    supportsTimeSeries: false,
    supportsCategorical: true,
    supportsMultipleSeries: false,
    supportsHierarchy: false,
    supportsGeography: false,
    supportsInteraction: true,
    supportsZoom: false,
    supportsTooltip: true,
    supportsDrilldown: true,
    supportsExport: true,
  },
  radar: {
    id: "radar",
    name: "Radar Chart",
    description: "Compares multiple quantitative variables.",
    bestFor: ["multi_dimensional_comparison", "profile_comparison"],
    requiredDimensions: 1, // multiple dimensions on axes, but usually treated as 1 categorical field
    requiredMeasures: 3,
    minimumDataPoints: 3,
    supportsTimeSeries: false,
    supportsCategorical: true,
    supportsMultipleSeries: true,
    supportsHierarchy: false,
    supportsGeography: false,
    supportsInteraction: true,
    supportsZoom: false,
    supportsTooltip: true,
    supportsDrilldown: false,
    supportsExport: true,
  },
  scatter: {
    id: "scatter",
    name: "Scatter Plot",
    description: "Shows relationships and distribution between two variables.",
    bestFor: ["relationship", "correlation", "distribution"],
    requiredDimensions: 0,
    requiredMeasures: 2,
    minimumDataPoints: 5,
    supportsTimeSeries: false,
    supportsCategorical: false,
    supportsMultipleSeries: true,
    supportsHierarchy: false,
    supportsGeography: false,
    supportsInteraction: true,
    supportsZoom: true,
    supportsTooltip: true,
    supportsDrilldown: false,
    supportsExport: true,
  },
  heatmap: {
    id: "heatmap",
    name: "Heatmap",
    description: "Shows magnitude of a phenomenon as color in two dimensions.",
    bestFor: ["intensity_matrix", "time_x_category"],
    requiredDimensions: 2,
    requiredMeasures: 1,
    minimumDataPoints: 4,
    supportsTimeSeries: true,
    supportsCategorical: true,
    supportsMultipleSeries: false,
    supportsHierarchy: false,
    supportsGeography: false,
    supportsInteraction: true,
    supportsZoom: true,
    supportsTooltip: true,
    supportsDrilldown: true,
    supportsExport: true,
  },
  treemap: {
    id: "treemap",
    name: "Treemap",
    description: "Displays hierarchical data as a set of nested rectangles.",
    bestFor: ["hierarchical_composition"],
    requiredDimensions: 1,
    requiredMeasures: 1,
    minimumDataPoints: 2,
    supportsTimeSeries: false,
    supportsCategorical: true,
    supportsMultipleSeries: false,
    supportsHierarchy: true,
    supportsGeography: false,
    supportsInteraction: true,
    supportsZoom: true,
    supportsTooltip: true,
    supportsDrilldown: true,
    supportsExport: true,
  }
};
