import {
  pgTable,
  uuid,
  text,
  varchar,
  timestamp,
  integer,
  jsonb,
  pgEnum,
  index,
  customType,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { employees } from "./org";
import { organizations } from "./org";
import { competencies } from "./competency";

// pgvector column type. Dimension must match EMBEDDING_MODEL output
// (1536 for OpenAI text-embedding-3-small; adjust to match your provider).
const vector = customType<{ data: number[]; driverData: string }>({
  dataType(config) {
    const dims = (config as { dimensions?: number } | undefined)?.dimensions ?? 1536;
    return `vector(${dims})`;
  },
  toDriver(value: number[]) {
    return `[${value.join(",")}]`;
  },
  fromDriver(value: string) {
    return value
      .slice(1, -1)
      .split(",")
      .map((v) => Number(v));
  },
});

export const documentStatusEnum = pgEnum("document_status", [
  "UPLOADED",
  "PROCESSING",
  "INDEXED",
  "FAILED",
]);

export const documents = pgTable(
  "documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    uploadedByEmployeeId: uuid("uploaded_by_employee_id").references(() => employees.id, {
      onDelete: "set null",
    }),
    title: varchar("title", { length: 500 }).notNull(),
    fileType: varchar("file_type", { length: 20 }).notNull(), // pdf | pptx | docx | txt
    fileHash: varchar("file_hash", { length: 64 }).notNull(),
    mimeType: varchar("mime_type", { length: 100 }),
    sizeBytes: integer("size_bytes"),
    storageKey: text("storage_key").notNull(),
    accessScope: varchar("access_scope", { length: 30 }).notNull().default("ORGANIZATION"), // ORGANIZATION | DEPARTMENT | PUBLIC
    competencyId: uuid("competency_id").references(() => competencies.id, {
      onDelete: "set null",
    }),
    status: documentStatusEnum("status").notNull().default("UPLOADED"),
    processingError: text("processing_error"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => ({
    orgIdx: index("documents_org_idx").on(t.organizationId),
    statusIdx: index("documents_status_idx").on(t.status),
  })
);

export const documentChunks = pgTable(
  "document_chunks",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => documents.id, { onDelete: "cascade" }),
    chunkIndex: integer("chunk_index").notNull(),
    content: text("content").notNull(),
    pageNumber: integer("page_number"),
    section: varchar("section", { length: 255 }),
    tokenCount: integer("token_count"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => ({
    documentIdx: index("document_chunks_document_idx").on(t.documentId),
  })
);

export const documentEmbeddings = pgTable(
  "document_embeddings",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    chunkId: uuid("chunk_id")
      .notNull()
      .references(() => documentChunks.id, { onDelete: "cascade" })
      .unique(),
    embedding: vector("embedding", { dimensions: 1536 }),
    embeddingModel: varchar("embedding_model", { length: 100 }).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => ({
    // IVFFlat index for approximate nearest-neighbour search. Created via raw SQL
    // migration (drizzle-kit does not yet generate vector index DDL) — see
    // drizzle/0001_vector_indexes.sql generated by `npm run db:generate` and the
    // manual addition documented in BACKEND_ARCHITECTURE.md.
    chunkIdx: index("document_embeddings_chunk_idx").on(t.chunkId),
  })
);

// AI interaction log — every tutor / analytics-assistant / MCQ-generation call,
// for observability, cost tracking and prompt-injection auditing (FR-27, design.md #13).
export const aiInteractions = pgTable(
  "ai_interactions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    employeeId: uuid("employee_id").references(() => employees.id, { onDelete: "set null" }),
    interactionType: varchar("interaction_type", { length: 50 }).notNull(), // TUTOR | MCQ_GEN | ANALYTICS_ASSISTANT
    prompt: text("prompt"),
    retrievedChunkIds: jsonb("retrieved_chunk_ids").$type<string[]>(),
    response: text("response"),
    model: varchar("model", { length: 100 }),
    latencyMs: integer("latency_ms"),
    tokensUsed: integer("tokens_used"),
    flaggedForInjection: integer("flagged_for_injection").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => ({
    employeeIdx: index("ai_interactions_employee_idx").on(t.employeeId),
    typeIdx: index("ai_interactions_type_idx").on(t.interactionType),
  })
);

export const documentsRelations = relations(documents, ({ many }) => ({
  chunks: many(documentChunks),
}));

export const documentChunksRelations = relations(documentChunks, ({ one }) => ({
  document: one(documents, { fields: [documentChunks.documentId], references: [documents.id] }),
  embedding: one(documentEmbeddings, {
    fields: [documentChunks.id],
    references: [documentEmbeddings.chunkId],
  }),
}));
