export const DATA_SOURCES = [
  {
    id: "mospi-api",
    name: "MoSPI API Platform",
    organization: "MoSPI",
    type: "api",
    officialUrl: "https://api.mospi.gov.in/",
    integrationMode: "live-if-token",
    enabled: true,
    requiresCredentials: true,
  },
  {
    id: "esankhyiki",
    name: "eSankhyiki",
    organization: "MoSPI",
    type: "catalogue",
    officialUrl: "https://esankhyiki.mospi.gov.in/",
    integrationMode: "html-ingest",
    enabled: true,
    requiresCredentials: false,
  },
  {
    id: "unitdata",
    name: "MoSPI UnitData",
    organization: "MoSPI",
    type: "api",
    officialUrl: "https://microdata.gov.in/",
    integrationMode: "credentials",
    enabled: true,
    requiresCredentials: true,
  },
  {
    id: "nssta",
    name: "NSSTA",
    organization: "NSSTA",
    type: "web-ingest",
    officialUrl: "https://nssta.gov.in/",
    integrationMode: "html-ingest",
    enabled: true,
    requiresCredentials: false,
  },
  {
    id: "igot",
    name: "iGOT Karmayogi",
    organization: "DoPT / iGOT",
    type: "api",
    officialUrl: "https://www.igotkarmayogi.gov.in/",
    integrationMode: "mock-until-authorized",
    enabled: true,
    requiresCredentials: true,
  },
  {
    id: "datagovin",
    name: "data.gov.in",
    organization: "NIC / MeitY",
    type: "api",
    officialUrl: "https://www.data.gov.in/",
    integrationMode: "optional",
    enabled: true,
    requiresCredentials: true,
  },
] as const;
