import { officialRepo } from "@/db/official-store";
import { basicStats, numericColumn } from "@/lib/lab/analyze";

export function selectDatasetForQuestion(question: string) {
  const q = question.toLowerCase();
  const datasets = officialRepo.listDatasets();
  const hit = datasets.find((d) => {
    const hay = `${d.name} ${d.theme} ${d.category}`.toLowerCase();
    return hay.split(/\s+/).some((token) => token.length > 2 && q.includes(token));
  });
  if (q.includes("wpi")) return officialRepo.getDataset("ds-wpi") ?? hit ?? null;
  return hit ?? datasets.find((d) => d.recordCount > 0) ?? null;
}

export function factsFromDataset(datasetId: string) {
  const dataset = officialRepo.getDataset(datasetId);
  const records = officialRepo.allRecords(datasetId);
  const columns = new Set<string>();
  for (const row of records) Object.keys(row.payload).forEach((k) => columns.add(k));
  const numeric = [...columns]
    .map((column) => ({ column, ...basicStats(numericColumn(records, column)) }))
    .filter((item) => item.count > 0);

  return {
    dataset,
    recordCount: records.length,
    sample: records.slice(0, 12).map((row) => row.payload),
    numeric,
    retrievedAt: records[0]?.retrievedAt ?? dataset?.lastUpdated ?? new Date().toISOString(),
    source: dataset?.source,
    sourceUrl: dataset?.sourceUrl,
  };
}

export function interpretFacts(question: string, facts: ReturnType<typeof factsFromDataset>) {
  if (!facts.dataset) {
    return "No matching synchronized dataset. Numbers cannot be generated by the model.";
  }
  if (facts.recordCount === 0) {
    return `Dataset “${facts.dataset.name}” is registered from ${facts.source}, but it has 0 numeric records. Awaiting authorized API credentials or an official CSV ingest. The model did not invent values.`;
  }
  const n = facts.numeric[0];
  const extra = n
    ? ` Observed ${n.column}: n=${n.count}, min=${n.min}, max=${n.max}, mean=${n.mean?.toFixed(3)}.`
    : " No numeric columns were present in stored records; only metadata/sample rows are shown.";
  return `Question: ${question}. Source ${facts.source}. ${facts.recordCount} stored records.${extra} Interpretation uses only these retrieved facts.`;
}
